# IP/PORTS
UDP_IP = ""
LOCAL_UDP_IP = "127.0.0.1"
UDP_PORT = 4444

# HEADER DEFINITIONS
LEFT_ARM_HEADER = "l_arm_guitar"
RIGHT_ARM_HEADER = "r_arm_guitar"
MEASURE_TIME_HEADER = "measure_time_guitar"
HEADER_DELIMITER = '#'